add_library(sink STATIC sink.cpp)
target_include_directories(sink PUBLIC ${CMAKE_SOURCE_DIR}/include/sink)
target_link_libraries(sink PUBLIC cppzmq)
target_link_libraries(sink PRIVATE Boost::boost)
target_link_libraries(sink PRIVATE spdlog::spdlog)
target_link_libraries(sink PRIVATE torrent-rasterbar)

add_executable(syncfs syncfs.cpp files.cpp discovery.cpp monitor.cpp)
target_include_directories(syncfs PRIVATE ${CMAKE_SOURCE_DIR}/include)
target_link_libraries(syncfs PRIVATE sink)
target_link_libraries(syncfs PRIVATE cppzmq)
target_link_libraries(syncfs PRIVATE spdlog::spdlog)
